[project]
name = "scripts"
version = "0.1.0"
description = "misc scripts I use on linux systems"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = []

[tool.uv]
dev-dependencies = [
    "ruff>=0.7.0",
]
