---                                                                                                                                          
- hosts: all                                                                                                                                 
  # become: true                                                                                                                             
  # vars:                                                  
  #   tool_name: vscode                                      
  pre_tasks:
    - name: updating cache
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 3600

  tasks:

    - name: installing pipenv deps
      become: true
      package:
        name: python3-pip
        state: present

    - name: installing pipenv
      pip:
        name: pipenv
        executable: pip3
        state: present

    - name: installing pipenv env
      import_role:
        name: elreydetoda.pipenv
      vars:
        dev_env: true
