# cmd:ansible-galaxy "${ansible_type}" install -r
# i.e.:ansible-galaxy collection install -r                                                                                                  
# i.e.:ansible-galaxy roll install -r
                                                                                                                                             
collections:            
  # - name: community.general                               

roles:                                                                                                                                       
  - name: elreydetoda.pipenv
  #   version: 1.5.0
